### ISSUE TITLE
dark mode for your website

### ISSUE THREAD

**Issue by victorhck** [k9mail/k9mail.app#127]
Hello!
A great new place for this great app!
But, I miss a dark mode for your website.
Maybe this can be helpful: https://francisoliver.dev/blog/dark-mode-in-jekyll

Greetings

**Comment by AnXh3L0** [comment]
Hi @victorhck, thanks for opening this issue. Currently, a dark mode is not a feature I would consider a priority as there's quite a few other things still not working. Until then, this is lower priority.

**Comment by victorhck** [comment]
Ok!
Anyway, Great work! ;)
