### ISSUE TITLE
Developer info section

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k9mail.app#15]
This is a big project but, we should link to / provide developer info on:
- [x] Intents we provide and handle
- [ ] Content Providers we expose
- [x] List of RFCs
- [ ] APIs we support (e.g. OpenKeychain PGP)
- [ ] APIs we expose (i.e. https://github.com/k9mail/k-9/wiki/ThirdPartyApplicationIntegration )
- [ ] RFCs we implement (subsection basis) and how that applies to the app
- [x] Architecture of the app (high-level)

This will probably involve:
- [ ] Researching relevant RFCs
- [ ] Writing tests for K-9 to ensure we follow the RFCs
- [ ] Writing tests for K-9's APIs we expose to ensure we provide a consistent interface
- - [ ] Content Providers
- - [ ] Intents
- [ ] Building documentation for K-9 and linking to it
- [ ] Providing code samples for API and Intent usage

I'm happy to accept PRs that provide partial support for some of this.

**Comment by cketti** [comment]
This should probably live in the wiki, not the website.
