### ISSUE TITLE
Does k-9mail not support desktop corner notifications?

### ISSUE THREAD

**Issue by biange200** [k9mail/k9mail.app#198]
k-9mail does not support desktop corner notification alerts compared to fairemail
fairemail can see how many new emails there are on the desktop, can this feature be added?

**Comment by AnXh3L0** [comment]
@biange200 This is not the correct repository to open this issue in, but first of all, K9 is not a desktop app, it's an Android app.

**Comment by biange200** [comment]
> @biange200 This is not the correct repository to open this issue in, but first of all, K9 is not a desktop app, it's an Android app.

![IMG_20230529_181632.jpg](https://github.com/k9mail/k9mail.app/assets/37582806/a04a086c-c792-4995-8ebb-5bba368bb42e)

我说的是手机桌面角标通知，这个fairemail支持，k-9mail不支持

**Comment by AnXh3L0** [comment]
Wrong repository, please open an issue on thundernest/k-9.

**Comment by biange200** [comment]
> @biange200 This is not the correct repository to open this issue in, but first of all, K9 is not a desktop app, it's an Android app.

I'm talking about the number of message notifications displayed on the phone's desktop
