### ISSUE TITLE
Google-Mail Account cannot be added 

### ISSUE THREAD

**Issue by overcuriousity** [k9mail/k9mail.app#210]
I cannot add my gmail account since i added the extended security program.

Google provided the following error details:

Fehler 400: policy_enforced
Anfragedetails: login_hint=hidden response_type=code redirect_uri=com.fsck.k9:/oauth2redirect state=xiK3EHSip1H-dUr3Ksvu_g code_challenge_method=S256 nonce=351AVKSDkspER9ECDEjjew client_id=262622259280-hhmh92rhklkg2k1tjil69epo0o9a12jm.apps.googleusercontent.com code_challenge=KtGro3xjH45aNezajvBiu2S35c_rowL3e4w2LYq2U9c access_type=offline scope=https://mail.google.com/

**Comment by cketti** [comment]
This is the repository for the website, not the app.

Please use the [forum](https://forum.k9mail.app/) for support requests.
