### ISSUE TITLE
Request for functionality. Being able to print an email. v6.901

### ISSUE THREAD

**Issue by franco27** [k9mail/k9mail.app#220]
Hello,

I wanted to print several emails from your application and I was surprised not to find a menu to print the email.

I tried using the Share button or menu and chose the printing application. But each time, it's the HTML programming code version of the email that is shown in the preview.

I am really surprised not to find this printing functionality.

**Comment by cketti** [comment]
This is the repository for the K-9 Mail website, not the repository for the app itself.

A feature request for printing already exists: https://github.com/thunderbird/thunderbird-android/issues/1062
