### ISSUE TITLE
Add a Thunderbird for Android Launch banner

### ISSUE THREAD

**Issue by kewisch** [k9mail/k9mail.app#233]
With Thunderbird for Android launching soon, we believe it would be a good opportunity to make users more aware of the launch. For a limited time we'd like to do a takeover on the main page that points directly to Thunderbird for Android's play store entry. If we have both f-droid and play store ready by the release we could do both.

@AnXh3L0 I wanted to give you a heads up on this in case you had questions or feedback.

**Comment by kewisch** [comment]
![image](https://github.com/user-attachments/assets/0fe882d1-7663-4bed-89cd-894d06014d33)

This is the first draft for the banner, which would go up at the top of the site replacing the area where it also says "Advanced Email for Android" and shows the device screenshot.

I've asked design to take another look if we can make the messaging more clear, so users understand why they are seeing this instead of a K-9 Mail install. The general idea is that users who might enjoy K-9 Mail should check out Thunderbird for Android.

**Comment by AnXh3L0** [comment]
Hi @kewisch , thanks for the heads up. I think we can probably replace the whole header/hero section with content specifically pointing to Thunderbird Mobile and clarifying why people are seeing that content on the K9 website. What do you think? Can TB Design team think of a hero section for this? The website is using Bootstrap IIRC. Thanks!

**Comment by laurelterlesky** [comment]
Hi, That big banner is actually intended for our Thunderbird blog site - not for K9. 

We're aiming to put a small text banner at the top of the K9mail.app site like this:
![Screenshot 2024-10-28 at 14 46 08](https://github.com/user-attachments/assets/17b5818f-1d19-4beb-863c-0ede4500b666)

**Comment by laurelterlesky** [comment]
One of my team members can help with the css styling if you need. It will link to https://www.thunderbird.net/mobile

**Comment by kewisch** [comment]
Ah oops, that explains why I was confused, sorry for sharing the wrong screenshot.

**Comment by kewisch** [comment]
Laurel can provide the colors - minor comments on the design, if we could use lowercase thunderbird.net in the link, and link to `https://www.thunderbird.net/mobile` it would be great. We're releasing the updated website on Wednesday.

**Comment by micahilbery** [comment]
> Ah thanks @laurelterlesky, that makes more sense. I can implement that tomorrow. Can you share the hex colors please? Thanks!

Ah sorry, I didn't see this. I had a go at it in #234. Feel free to supersede it if you have another way you'd prefer this implemented. If so you can use the hex colors and general design from that PR.
