### ISSUE TITLE
Support forum: activation email never received

### ISSUE THREAD

**Issue by Iey4iej3** [k9mail/k9mail.app#235]
I tried to register at https://forum.k9mail.app/ several times, and always failed to receive the activation email from my outlook email address. I look at the Spam folder, and it is not there.

**Comment by AnXh3L0** [comment]
Hi @Iey4iej3, please note that this repository/issue tracker is only for the k9mail.app website itself, and not for other services. In any case, I am pinging @cketti here since he might know more regarding the forum.

**Comment by cketti** [comment]
Microsoft is blocking our mail server. 

> 5.7.1 Unfortunately, messages from [109.230.236.132] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.


I don't have time (or, frankly, the will) to deal with this. Other email providers work fine.
