### ISSUE TITLE
Rebranding / relationship to Thunderbird?

### ISSUE THREAD

**Issue by justinacolmena** [k9mail/k9mail.app#240]
I was a little bit confused. Snafu updating F-Droid versus Official Google Android Store, Google enhanced security etc.

Then I downloaded Thunderbird mobile, exact same app as far as I could tell. QR code to copy settings and passwords over from desktop, no questions asked. The mailman is getting concerned about dog bites.

Scenario: PC unattended, bathroom break, cop walks in with an off-the-books brokered cell phone, QR code at the ready, not just NSA, we're local and we've got to be able to "supervise" a suspect's email without the official hassle of a warrant in court and all that, you know.

**Comment by kewisch** [comment]
More information on this topic is available here: https://support.mozilla.org/en-US/kb/thunderbird-android-8-faq#w_what-is-the-difference-between-k-9-mail-and-thunderbird-for-android-they-look-the-same

The QR code doesn't have passwords enabled by default and there is a warning on desktop before enabling them if you are concerned about that scenario. You might also consider locking your PC when you take a break.

**Comment by justinacolmena** [comment]
> You might also consider locking your PC when you take a break.

Yeah I think I have a lot more than my PC to lock up.
