### ISSUE TITLE
More prominent display of PGP/MIME documentation

### ISSUE THREAD

**Issue by mikini** [k9mail/k9mail.app#36]
The rather comprehensive information at https://k9mail.github.io/documentation/security/pgpmime_current.html is buried very deep. It took me some tries to find it even when looking for it. I think I ignored the bullet list with the OpenPGP / PGP/MIME link at https://k9mail.github.io/documentation/security.html taking it for an external reference to the specifications.

The complete beginner would probably also have good use of a more gentle introduction. OpenKeyChain has a nice tutorial/howto on https://www.openkeychain.org/howto/ which could be referenced.

**Comment by philipwhiuk** [comment]
See k9mail/k-9#2054 for things we should try to cover (without being too OKc specific)

**Comment by philipwhiuk** [comment]
Added a link to PGP/MIME section from About page - afb4f81223e8f37ce944d408d6c91dae23887eb6

**Comment by philipwhiuk** [comment]
Expanded content of security page to make it more clear what information is available - 2f38d6a6bacd155e195b83d5fd351c1036d8d67d

**Comment by DarkerSideUK** [comment]
Might also be worth adding a little something to the "reading email" page:

https://k9mail.github.io/documentation/reading.html

about the padlock icon* that relates to the signature/encryption of the message. Even if it's just a link to the images on:

https://k9mail.github.io/documentation/security/pgpmime.html

*icon appears next to the star email icon on accounts with pgp enabled.
